services:
  app:
    build: .
    ports:
      - '8083:8083'
    environment:
      - 'MONGO_HOST=mongodb'
      - 'JWT_SECRET=${JWT_SECRET}'
      - 'AZURE_SENDER_ADDRESS=${AZURE_SENDER_ADDRESS}'
      - 'AZURE_EMAIL_CONNECTION_STRING=${AZURE_EMAIL_CONNECTION_STRING}'
    depends_on:
      - mongodb
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27018:27017'
